config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  resources :posts
  resources :profiles, only: [:show,:new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many_attached :images
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :name, presence: true
  validates :learning_history, presence: true
  validates :purpose, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy

  delegate :name, :learning_history, :purpose, :image, to: :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :force_redirect_unless_my_post, only: [ :edit, :update, :destroy]


  def index
    @posts = Post.all
  end

  def show
  end

  def new
    return redirect_to new_profile_path, alert: "プロフィールを登録して下さい" if current_user.profile.blank?
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to root_path, notice: "投稿に成功しました"
    else
      render :new
    end
  end

  def update
    if @post.update(post_param)
      redirect_to root_path, notice: "投稿を更新しました"
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to root_path, notice: "投稿を削除しました"
    else
      redirect_to root_path, alert: "投稿を削除出来ませんでした"
    end
  end

  private

  def post_params
    params.require(:post).permit(
      :content,
      images: []
    )
  end

  def find_post
    @post = Post.find(params[:id])
  end

  def force_redirect_unless_my_post
    return redirect_to root_path, aleart: "自分の投稿ではありません" if @post.user != current_user
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_profile, only: [:show, :edit, :update]

  def show
  end

  def new
    return redirect_to edit_profile_path(current_user.profile) if current_user.profile.present?
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    if @profile.save
      redirect_to root_path, notice: "プロフィールの登録が完了しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    @profile = Profile.new(profile_params)
    if @profile.update
      redirect_to root_path, notice: "プロフィールの更新が完了しました"
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def find_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(
      :name, :learning_history, :purpose, :image
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
    <%= render 'shared/header'%>
    <%= render 'shared/toast' %>
    <%= yield %>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <%= f.text_area :content, rows: 5 %>
  <%= f.file_field :images, multiple: true %><br>
  <div class="submit-block">
    <%= f.submit "投稿", class: "btn" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div>
  <h1>投稿編集</h1>
  <%= render 'form' %>
</div>

app/views/posts/new.html.erb
<div>
  <h1>新規投稿</h1>
  <%= render 'form' %>
</div>

app/views/profiles/_form.html.erb
<%= form_with model: @profile, local: true do |f| %>

    <%= f.label :name, "名前" %><br />
    <%= f.text_field :name %>

    <%= f.label :learning_history, "学習歴(年)" %><br />
    <%= f.number_field :learning_history %><br />

    <%= f.label :purpose, "目的" %><br />
    <%= f.text_field :purpose %>

    <%= f.label :image, "プロフィール写真" %><br />
    <%= f.file_field :image %>

    <% if f.object.image.attached? %>
      <p>現在のプロフィール画像</p>
      <div class="image-preview">
        <%= image_tag f.object.image %>
      </div>
    <% end %>
    <div class="submit-block">
      <%= f.submit "作成", class: "btn" %>
    </div>

<% end %>

app/views/profiles/edit.html.erb
<div class="form-body">
  <h1>プロフィール編集</h1>
  <%= render 'form' %>
</div>

app/views/profiles/new.html.erb
<div class="form-body">
  <h1>プロフィール作成</h1>
  <%= render 'form' %>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
  <p>©️ 2020 Rails Community</p>
</div>

app/views/shared/_header.html.erb
<div id="header">
  <div class="logo">
    <%= link_to image_tag("rails-community.png"), root_path %>
  </div>
  <div class="link">
    <ul id="nav">
      <% if user_signed_in? %>
        <li>
          <%= link_to "投稿する", new_post_path %>
        </li>
        <li>
          <%= link_to "プロフィール", new_profile_path %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_toast.html.erb
<% if flash[:notice].present? %>
  <div class="toast">
    <div class="notice"><%= notice %></div>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="toast">
    <div class="alert"><%= alert %></div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<% if current_user.present? %>
  <%= "ログイン中：#{current_user.name}" %>
<% end %>
<div class="content-wrapper">
  <div class="content-block">
    <% @posts.each do |p| %>
      <div class="content">
        <div class="user-about">
          <div class="image">
            <% if p.user.image.attached? %>
              <%= image_tag p.user.image %>
            <% else %>
              <%= image_tag "nouser.png" %>
            <% end %>
          </div>
          <div class="profile">
            <div class="name-history">
              <div class="name">
                <%= p.user.name %>
              </div>
              <div class="learning-history">
                <%= "学習歴：　#{p.user.learning_history}１年" %>
              </div>
            </div>
            <div class="purpose">
            <%= "目的： #{p.user.purpose}" %>
            </div>
          </div>
        </div>
        <div class="text">
          <p><%= p.content %></p>
        </div>
        <% if p.images.attached? %>
          <div class="images">
            <% p.images.each do |image| %>
              <%= image_tag image %>
            <% end %>
          </div>
        <% end %>
        <div class="action-menu">
          <div class="like">
            <i class="far fa-heart like-icon"></i>
            <span>0</span>
          </div>
          <div class="comment">
            <i class="far fa-comment-alt"></i>
            <span>0</span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="sidebar">
    <div class="box"></div>
    <div class="box"></div>
  </div>
</div>